"""JetBrains Junie transformer — one ``.junie/AGENTS.md`` per stack.

Phase 5 deliverable per `docs/02-implementation-plan.md` §8 task 3.

Output contract
---------------

For each stack, this transformer writes a single Markdown file at
``<dist_root>/stacks/<stack_id>/junie/AGENTS.md``. The file is dropped verbatim into a consumer
repo's ``.junie/AGENTS.md`` by the Phase-8 sync tool.

Format matches JetBrains' own `junie-guidelines` repository
(``JetBrains/junie-guidelines/guidelines/java/spring-boot/guidelines.md``): a top-level intro,
followed by a flat **numbered list (1..N)** of one rule per item, each item carrying:

* A bold one-line title (the rule's ``title``).
* A short paragraph of context (derived from the rule's body).
* A "Rules" sub-list summarizing the enforced standards extracted from H3 ``### 2.X`` blocks.

The numbered-list shape is what Junie's IDE-side parser expects; the layered-section split used
by Copilot/Claude is replaced with a flat ordering. Dependency-first topological order is still
honored so prerequisites appear with lower numbers than dependents.
"""
from __future__ import annotations

import dataclasses
import logging
import pathlib
import re
from typing import Iterable, List, Optional

from compiler.core.build_graph import topo_sort_relaxed
from compiler.core.logging_setup import get_logger, log_event
from compiler.core.parse_source import SourceRule
from compiler.core.stack_filter import Stack

TARGET_ID = "junie"
OUTPUT_RELATIVE_DIR = "junie"
OUTPUT_FILENAME = "AGENTS.md"


@dataclasses.dataclass(frozen=True)
class EmittedFile:
    """Record of one written file."""

    target_id: str
    stack_id: str
    output_path: pathlib.Path
    relative_output_path: str
    bytes_written: int
    rule_count: int


def _filter_target_rules(rules: Iterable[SourceRule], target_id: str) -> List[SourceRule]:
    return [r for r in rules if r.target_tools.is_enabled(target_id)]


def _topological_order(rules: List[SourceRule]) -> List[SourceRule]:
    if not rules:
        return []
    return topo_sort_relaxed(rules)


_CONTEXT_HEADING_RE = re.compile(r"^##\s+1\.\s+Context\s*(?:&|and)\s*Architectural Intent\s*$", re.MULTILINE)
_ENFORCED_HEADING_RE = re.compile(r"^##\s+2\.\s+Enforced Standards.*$", re.MULTILINE)
_NEXT_H2_RE = re.compile(r"^##\s+\d", re.MULTILINE)
_H3_RULE_RE = re.compile(
    r"^###\s+\d+\.\d+\.\s+(?P<rule>.+?)\s*$",
    re.MULTILINE,
)


def _extract_context_paragraph(body: str) -> str:
    """Returns the first non-empty paragraph of §1 Context & Architectural Intent.

    Falls back to the first paragraph of the body if the heading is absent.
    """
    m = _CONTEXT_HEADING_RE.search(body)
    start = m.end() if m else 0
    # End at the next H2 heading.
    rest = body[start:]
    next_h2 = _NEXT_H2_RE.search(rest)
    section = rest[: next_h2.start()] if next_h2 else rest
    # First non-empty paragraph (split on blank line).
    for para in re.split(r"\n\s*\n", section.strip()):
        para = para.strip()
        if para and not para.startswith("#"):
            return _flatten_paragraph(para)
    return ""


def _flatten_paragraph(text: str) -> str:
    """Collapses internal newlines and excess whitespace so the paragraph reads as one line."""
    return re.sub(r"\s+", " ", text).strip()


def _extract_enforced_rule_titles(body: str) -> List[str]:
    """Returns the H3 ``### 2.X. <title>`` titles inside §2 Enforced Standards."""
    m = _ENFORCED_HEADING_RE.search(body)
    if not m:
        return []
    start = m.end()
    rest = body[start:]
    next_h2 = _NEXT_H2_RE.search(rest)
    section = rest[: next_h2.start()] if next_h2 else rest
    return [match.group("rule").strip().rstrip(".") for match in _H3_RULE_RE.finditer(section)]


def render_junie_agents_md(rules: List[SourceRule], stack: Stack) -> str:
    """Renders the Junie numbered-list AGENTS.md for one stack. Pure function."""
    target_rules = _filter_target_rules(rules, TARGET_ID)
    ordered = _topological_order(target_rules)

    parts: List[str] = []
    parts.append(f"# {stack.human_name} Guidelines (JetBrains Junie)\n\n")
    parts.append(
        "This file is generated by `engineering-standards-central` from canonical source rules.\n"
        "Do not edit by hand. JetBrains Junie reads `.junie/AGENTS.md` at the project root.\n\n"
    )
    parts.append(
        f"**Stack**: `{stack.id}` — {stack.human_name} (framework `{stack.framework}` "
        f"`{stack.framework_version}`).\n\n"
    )
    parts.append(f"**Rule count**: {len(ordered)} rule(s).\n\n")
    parts.append("---\n\n")

    if not ordered:
        parts.append("_No Junie-enabled rules ship to this stack._\n")
        return "".join(parts)

    for index, rule in enumerate(ordered, start=1):
        parts.append(f"{index}. **{rule.title}**\n\n")
        context = _extract_context_paragraph(rule.body)
        if context:
            parts.append(f"   {context}\n\n")
        enforced = _extract_enforced_rule_titles(rule.body)
        if enforced:
            parts.append("   Rules:\n\n")
            for sub in enforced:
                parts.append(f"   - {sub}\n")
            parts.append("\n")

    output = "".join(parts).rstrip() + "\n"
    return output


def emit_for_stack(
    rules: Iterable[SourceRule],
    stack: Stack,
    *,
    dist_root: pathlib.Path,
    logger: Optional[logging.Logger] = None,
) -> List[EmittedFile]:
    """Writes the Junie ``AGENTS.md`` for the stack."""
    if logger is None:
        logger = get_logger()

    rules_list = list(rules)
    target_rules = _filter_target_rules(rules_list, TARGET_ID)
    if not target_rules:
        log_event(
            logger,
            "skip",
            target=TARGET_ID,
            stack=stack.id,
            reason="no rules opt into junie for this stack",
        )
        return []

    content = render_junie_agents_md(rules_list, stack)
    out_dir = pathlib.Path(dist_root) / "stacks" / stack.id / OUTPUT_RELATIVE_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / OUTPUT_FILENAME
    out_path.write_text(content, encoding="utf-8")

    try:
        rel = str(out_path.resolve().relative_to(pathlib.Path(dist_root).resolve())).replace(
            "\\", "/"
        )
        rel_path = f"{dist_root}/{rel}" if str(dist_root) else rel
    except ValueError:
        rel_path = str(out_path).replace("\\", "/")

    record = EmittedFile(
        target_id=TARGET_ID,
        stack_id=stack.id,
        output_path=out_path,
        relative_output_path=rel_path,
        bytes_written=len(content.encode("utf-8")),
        rule_count=len(target_rules),
    )
    log_event(
        logger,
        "emit",
        target=TARGET_ID,
        stack=stack.id,
        output_path=rel_path,
        bytes=record.bytes_written,
        rule_count=record.rule_count,
    )
    return [record]


__all__ = [
    "EmittedFile",
    "OUTPUT_FILENAME",
    "OUTPUT_RELATIVE_DIR",
    "TARGET_ID",
    "emit_for_stack",
    "render_junie_agents_md",
]
