"""Universal AGENTS.md transformer — one ≤150-line root-level ``AGENTS.md`` per stack.

Phase 5 deliverable per `docs/02-implementation-plan.md` §8 task 4.

Output contract
---------------

For each stack, this transformer writes a single Markdown file at
``<dist_root>/stacks/<stack_id>/agents-md/AGENTS.md``. The file is dropped verbatim into the
consumer repo's root-level ``AGENTS.md`` by the Phase-8 sync tool.

AGENTS.md is the **cross-tool open standard** (per Architecture Upgrade Report §3.4): native
support across Codex CLI, GitHub Copilot, Cursor, Windsurf, Amp, Devin. The spec recommends
**≤150 lines** for context-budget efficiency.

Selection rules:

* Only rules with ``target_tools.agents_md == True`` AND ``activation.agents_md_priority == 'high'``
  are considered. ``medium`` and ``low`` rules are intentionally excluded.

Canonical sections (per the AGENTS.md spec):

1. **Tech Stack** — stack id, framework, pinned version, language.
2. **Commands** — small set of useful project commands (build, test, lint placeholders that the
   consumer overrides). The compiler emits stack-shape-agnostic placeholders; the consumer's
   own ``AGENTS.md`` (if any) overrides this section in practice.
3. **Code Style** — derived from the selected rules' titles, one-line per rule.
4. **Testing** — derived from rules in the ``test`` layer; falls back to a generic note.
5. **Boundaries** — what AI should and should not generate; derived from any rules with the
   ``architecture`` layer.

Length enforcement
------------------

If the generated file exceeds ``MAX_LINES`` (default 150), the transformer raises
``AgentsMdTooLongError`` with a diagnostic listing the rules contributing to the bloat and a
recommendation to demote some to ``medium`` priority in their source frontmatter. The CLI
catches this and exits 1 with the diagnostic on stderr.
"""
from __future__ import annotations

import dataclasses
import logging
import pathlib
from typing import Iterable, List, Optional

from compiler.core.build_graph import topo_sort_relaxed
from compiler.core.logging_setup import get_logger, log_event
from compiler.core.parse_source import SourceRule
from compiler.core.stack_filter import Stack

TARGET_ID = "agents_md"
OUTPUT_RELATIVE_DIR = "agents-md"
OUTPUT_FILENAME = "AGENTS.md"

# AGENTS.md spec recommendation. Strict cap; the build fails if the corpus exceeds this.
MAX_LINES = 150

# Layer that signals an architecture/boundary rule.
ARCHITECTURE_LAYER = "architecture"


class AgentsMdTooLongError(ValueError):
    """Raised when the generated AGENTS.md would exceed ``MAX_LINES``."""


@dataclasses.dataclass(frozen=True)
class EmittedFile:
    """Record of one written file."""

    target_id: str
    stack_id: str
    output_path: pathlib.Path
    relative_output_path: str
    bytes_written: int
    rule_count: int
    line_count: int


def _filter_target_rules(rules: Iterable[SourceRule]) -> List[SourceRule]:
    """Selects rules opting into ``agents_md`` AND with ``agents_md_priority: high``."""
    return [
        r
        for r in rules
        if r.target_tools.agents_md and r.activation.agents_md_priority == "high"
    ]


def _topological_order(rules: List[SourceRule]) -> List[SourceRule]:
    if not rules:
        return []
    return topo_sort_relaxed(rules)


def _one_liner(title: str) -> str:
    """Trims trailing period and ensures a single line."""
    t = title.strip()
    if t.endswith("."):
        t = t[:-1]
    return t


def _has_test_layer(rule: SourceRule) -> bool:
    return "test" in rule.scope.layers


def _has_architecture_layer(rule: SourceRule) -> bool:
    return ARCHITECTURE_LAYER in rule.scope.layers


def render_universal_agents_md(
    rules: List[SourceRule],
    stack: Stack,
    *,
    max_lines: int = MAX_LINES,
) -> str:
    """Renders the ≤150-line AGENTS.md for one stack. Pure function.

    Raises ``AgentsMdTooLongError`` if the rendered output would exceed ``max_lines``.
    """
    selected = _filter_target_rules(rules)
    ordered = _topological_order(selected)

    parts: List[str] = []
    parts.append(f"# AGENTS.md — {stack.human_name}\n\n")
    parts.append(
        "This file is generated by `engineering-standards-central`. It is the universal,\n"
        "tool-agnostic baseline; tool-specific files (`CLAUDE.md`, `.cursor/rules/*.mdc`,\n"
        "`.github/copilot-instructions.md`, `.junie/AGENTS.md`) carry the full rule corpus.\n\n"
    )

    parts.append("## Tech Stack\n\n")
    parts.append(f"- **Stack id**: `{stack.id}`\n")
    parts.append(f"- **Language**: {stack.language}\n")
    parts.append(f"- **Framework**: {stack.framework} {stack.framework_version}\n")
    parts.append(f"- **Compatible versions**: see the consumer's manifest (e.g., `pom.xml`).\n\n")

    parts.append("## Commands\n\n")
    parts.append(
        "Project-specific commands belong in the consumer repo's own AGENTS.md. If absent,\n"
        "AI agents fall back to language-conventional commands (e.g., `mvn verify`, `gradle build`,\n"
        "`npm test`, `pytest`). Override this section in the consumer to pin exact commands.\n\n"
    )

    parts.append("## Code Style\n\n")
    parts.append(
        f"Follow the canonical {stack.human_name} rules below. Each one-liner has a full source\n"
        f"under `engineering-standards-central/source/`. Full bodies ship to Cursor, Copilot,\n"
        f"Claude, and Junie.\n\n"
    )

    style_rules = [r for r in ordered if not _has_test_layer(r) and not _has_architecture_layer(r)]
    if style_rules:
        for rule in style_rules:
            parts.append(f"- {_one_liner(rule.title)}.\n")
        parts.append("\n")

    parts.append("## Testing\n\n")
    test_rules = [r for r in ordered if _has_test_layer(r)]
    if test_rules:
        for rule in test_rules:
            parts.append(f"- {_one_liner(rule.title)}.\n")
        parts.append("\n")
    else:
        parts.append(
            "Tests must accompany every behavioral change. Use slice tests for the controller\n"
            "and repository layers; reserve `@SpringBootTest` for end-to-end and Testcontainers\n"
            "integration tests. The Phase-6 ArchUnit fixtures enforce the Logic Holes at build time.\n\n"
        )

    parts.append("## Boundaries\n\n")
    arch_rules = [r for r in ordered if _has_architecture_layer(r)]
    if arch_rules:
        for rule in arch_rules:
            parts.append(f"- {_one_liner(rule.title)}.\n")
        parts.append("\n")
    else:
        parts.append(
            "Honor the layered architecture: controllers depend on services, services on\n"
            "repositories and domain; domain depends on nothing framework-bound.\n\n"
        )

    parts.append("## Where AI Should and Should Not Generate\n\n")
    parts.append(
        "| Path | AI may generate? |\n"
        "|---|---|\n"
        "| `src/main/java/.../controller/` | Yes, following the controller-layer rules above. |\n"
        "| `src/main/java/.../service/` | Yes, following the service-layer rules above. |\n"
        "| `src/main/java/.../repository/` | Yes, following the repository-layer rules above. |\n"
        "| `src/test/` | Yes, following the testing rules above. |\n"
        "| `.cursor/rules/`, `.github/copilot-instructions.md`, `CLAUDE.md`, `.junie/AGENTS.md` | "
        "No — regenerated by `engineering-standards-central`. |\n\n"
    )

    parts.append("## Provenance\n\n")
    parts.append(
        f"Generated from {len(ordered)} high-priority rule(s) in the\n"
        f"`engineering-standards-central` corpus. See `.standards-version` for the pinned\n"
        f"distribution release.\n"
    )

    output = "".join(parts)

    line_count = output.count("\n")
    if line_count > max_lines:
        contributing = [r.id for r in ordered]
        raise AgentsMdTooLongError(
            f"Universal AGENTS.md for stack '{stack.id}' would be {line_count} lines "
            f"(cap: {max_lines}). Demote some rules from "
            f"`agents_md_priority: high` to `medium` in their source frontmatter. "
            f"Currently contributing ({len(contributing)} rule(s)): "
            f"{', '.join(contributing)}. See `docs/authoring-guide.md` §7 (the priority rubric)."
        )

    return output


def emit_for_stack(
    rules: Iterable[SourceRule],
    stack: Stack,
    *,
    dist_root: pathlib.Path,
    logger: Optional[logging.Logger] = None,
    max_lines: int = MAX_LINES,
) -> List[EmittedFile]:
    """Writes the universal ``AGENTS.md`` for the stack."""
    if logger is None:
        logger = get_logger()

    rules_list = list(rules)
    content = render_universal_agents_md(rules_list, stack, max_lines=max_lines)
    line_count = content.count("\n")
    selected = _filter_target_rules(rules_list)

    out_dir = pathlib.Path(dist_root) / "stacks" / stack.id / OUTPUT_RELATIVE_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / OUTPUT_FILENAME
    out_path.write_text(content, encoding="utf-8")

    try:
        rel = str(out_path.resolve().relative_to(pathlib.Path(dist_root).resolve())).replace(
            "\\", "/"
        )
        rel_path = f"{dist_root}/{rel}" if str(dist_root) else rel
    except ValueError:
        rel_path = str(out_path).replace("\\", "/")

    record = EmittedFile(
        target_id=TARGET_ID,
        stack_id=stack.id,
        output_path=out_path,
        relative_output_path=rel_path,
        bytes_written=len(content.encode("utf-8")),
        rule_count=len(selected),
        line_count=line_count,
    )
    log_event(
        logger,
        "emit",
        target=TARGET_ID,
        stack=stack.id,
        output_path=rel_path,
        bytes=record.bytes_written,
        rule_count=record.rule_count,
        line_count=record.line_count,
        max_lines=max_lines,
    )
    return [record]


__all__ = [
    "AgentsMdTooLongError",
    "EmittedFile",
    "MAX_LINES",
    "OUTPUT_FILENAME",
    "OUTPUT_RELATIVE_DIR",
    "TARGET_ID",
    "emit_for_stack",
    "render_universal_agents_md",
]
