#!/usr/bin/env python3
"""Generate ``dist/README.md`` for a release.

Phase-7 deliverable per `docs/02-implementation-plan.md` §10 task 5.

The file is the human-facing index of the compiled distribution tree. The release workflow
runs this script AFTER ``python -m compiler --all-stacks --out dist/`` has populated the
``dist/stacks/`` subtree, so the generator can introspect the live tree and report exactly
what was produced (number of cursor rules per stack, presence/absence of each per-tool
target, etc.).

The generated file MUST reference ADR-0004 because the Phase-1 ``tree-shape`` CI job greps
for the string ``0004-single-repo-distribution`` and fails the build if it is missing.

CLI
---

::

    python tools/generate_dist_readme.py --version v2.4.0
    python tools/generate_dist_readme.py --version v2.4.0 --output dist/README.md
    python tools/generate_dist_readme.py --version v2.4.0 --dry-run

Exit codes:

* ``0`` success.
* ``1`` dist/ tree missing or malformed.
* ``2`` invocation error.

Output shape (single file, ~60 lines):

::

    > Auto-generated by tools/generate_dist_readme.py during the Phase-7 release
    > workflow. Do not edit by hand.
    > See docs/decision-records/0004-single-repo-distribution.md.

    # Engineering Standards — Distribution Index

    **Version**: `v2.4.0`
    **Released**: 2026-05-20
    **Changelog**: [CHANGELOG.md](./CHANGELOG.md)

    This directory is the **compiled output** of the Engineering Standards corpus...

    ## Stacks

    | Stack | Human Name | Cursor Rules | Other Targets |
    | ... |
"""
from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import sys
from typing import Dict, List, Optional, Sequence

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "dist" / "README.md"
DEFAULT_DIST_ROOT = REPO_ROOT / "dist"
STACKS_CATALOG_PATH = REPO_ROOT / "schemas" / "stacks.json"


def _load_known_stacks() -> List[Dict[str, str]]:
    """Loads the stack catalog from `schemas/stacks.json` (Phase-8 single source of truth).

    Phase-7 lesson §7-b: this previously duplicated the `compiler.core.stack_filter.STACKS`
    catalog as a sibling dict, kept in lock-step by a defense-in-depth test. Phase 8
    consolidated both into `schemas/stacks.json`; this helper extracts just the fields the
    README generator needs (`id`, `human_name`, `description`). The release workflow runs in
    a barebones environment (no `pip install -e compiler/`) so this generator still avoids
    the cross-import — but the underlying data is now identical to what the compiler reads.
    """
    with open(STACKS_CATALOG_PATH, "r", encoding="utf-8") as f:
        catalog = json.load(f)
    descriptors = catalog["properties"]["stacks"]["const"]
    return [
        {
            "id": desc["id"],
            "human_name": desc["human_name"],
            "description": desc["description"],
        }
        for desc in descriptors
    ]


KNOWN_STACKS: List[Dict[str, str]] = _load_known_stacks()

# Target-id → display label used when listing what's present in a stack's directory.
TARGET_LABELS = {
    "cursor": "Cursor MDC",
    "copilot": "Copilot",
    "claude": "Claude",
    "junie": "Junie",
    "agents-md": "AGENTS.md",
    "memory-bank": "Memory Bank",
    "archunit": "ArchUnit",
}


def _count_cursor_rules(stack_dir: pathlib.Path) -> int:
    rules_dir = stack_dir / "cursor" / "rules"
    if not rules_dir.is_dir():
        return 0
    return sum(1 for p in rules_dir.glob("*.mdc"))


def _present_targets(stack_dir: pathlib.Path) -> List[str]:
    """Returns the display labels for every target subtree that exists under stack_dir."""
    present: List[str] = []
    for target_id, label in TARGET_LABELS.items():
        target_dir = stack_dir / target_id
        if target_dir.is_dir():
            # Empty directory does NOT count as present (memory-bank scaffold etc. always emit files).
            if any(target_dir.iterdir()):
                present.append(label)
    return present


def _render(version: str, dist_root: pathlib.Path) -> str:
    today = datetime.date.today().isoformat()
    out: List[str] = []
    out.append("> Auto-generated by `tools/generate_dist_readme.py` during the Phase-7 release")
    out.append("> workflow. DO NOT edit by hand — your changes will be overwritten on the next")
    out.append("> release.")
    out.append(">")
    out.append("> See `docs/decision-records/0004-single-repo-distribution.md` for the design rationale.")
    out.append("")
    out.append("# Engineering Standards — Distribution Index")
    out.append("")
    out.append(f"- **Version**: `{version}`")
    out.append(f"- **Released**: {today}")
    out.append("- **Changelog**: [CHANGELOG.md](./CHANGELOG.md)")
    out.append("")
    out.append(
        "This directory is the **compiled output** of the Engineering Standards corpus "
        "authored under `source/`. Consumer repositories pull a stack's subtree via the "
        "`@org/standards-sync` CLI; see the consumer-side documentation for the sync flow."
    )
    out.append("")
    out.append(
        "Compiled artifacts are regenerated **only** by the release workflow under the "
        "`@engineering-standards-bot` GitHub App identity. Human-authored edits to any file inside "
        "this directory are rejected by the `dist-protection-lint` PR status check; see "
        "ADR-0004 for the four-guard protection model."
    )
    out.append("")
    out.append("## Stacks")
    out.append("")
    out.append("| Stack ID | Description | Cursor Rules | Other Targets |")
    out.append("| --- | --- | --- | --- |")

    stacks_root = dist_root / "stacks"
    if not stacks_root.is_dir():
        # Render the catalog with zero counts; the release workflow ALWAYS populates
        # dist/stacks/ first, but this guard makes the script safe to dry-run in any state.
        for entry in KNOWN_STACKS:
            out.append(f"| `{entry['id']}` | {entry['description']} | _(not built)_ | _(not built)_ |")
    else:
        for entry in KNOWN_STACKS:
            stack_dir = stacks_root / entry["id"]
            if not stack_dir.is_dir():
                out.append(
                    f"| `{entry['id']}` | {entry['description']} | _(missing)_ | _(missing)_ |"
                )
                continue
            cursor_count = _count_cursor_rules(stack_dir)
            cursor_cell = f"{cursor_count} `.mdc` file{'s' if cursor_count != 1 else ''}"
            targets = _present_targets(stack_dir)
            # Strip Cursor from "other" since it has its own column.
            targets_other = [t for t in targets if t != "Cursor MDC"]
            targets_cell = ", ".join(targets_other) if targets_other else "_(none)_"
            out.append(
                f"| `{entry['id']}` | {entry['description']} | {cursor_cell} | {targets_cell} |"
            )

    out.append("")
    out.append("## Layout")
    out.append("")
    out.append("Each `stacks/<stack-id>/` subdirectory follows the canonical layout:")
    out.append("")
    out.append("```text")
    out.append("stacks/<stack-id>/")
    out.append("├── cursor/")
    out.append("│   └── rules/                 # Cursor MDC files — one .mdc per applicable rule.")
    out.append("├── copilot/")
    out.append("│   └── copilot-instructions.md # Concatenated rules for GitHub Copilot.")
    out.append("├── claude/")
    out.append("│   └── CLAUDE.md              # Concatenated rules for Claude Skills.")
    out.append("├── junie/")
    out.append("│   └── AGENTS.md              # Numbered-list format for JetBrains Junie.")
    out.append("├── agents-md/")
    out.append("│   └── AGENTS.md              # Universal AGENTS.md (≤150 lines).")
    out.append("└── memory-bank/               # Six-file Memory Bank scaffold.")
    out.append("```")
    out.append("")
    out.append("## How to consume")
    out.append("")
    out.append("Run the consumer sync CLI from the root of your project:")
    out.append("")
    out.append("```bash")
    out.append("npx @org/standards-sync")
    out.append("```")
    out.append("")
    out.append(
        "The CLI detects your stack from `pom.xml` / `package.json` / `pyproject.toml`, "
        "resolves the pinned version from `.standards-version` (or the latest release tag), "
        "and copies the matching `stacks/<stack-id>/` subtree into your project's "
        "conventional locations. See the `@org/standards-sync` README for details."
    )
    out.append("")
    out.append("## Releases")
    out.append("")
    out.append("Tag history:")
    out.append("")
    out.append("```bash")
    out.append("git tag --list 'v*' --sort=-version:refname")
    out.append("```")
    out.append("")
    out.append("Audit the bot-authored release commits:")
    out.append("")
    out.append("```bash")
    out.append("git log --author='engineering-standards-bot' --pretty='%h %ai %s' -- dist/")
    out.append("```")
    out.append("")
    return "\n".join(out)


def _make_arg_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="generate_dist_readme.py",
        description=(
            "Generate dist/README.md for a release. Used by the Phase-7 release workflow "
            "(docs/02-implementation-plan.md §10 task 5)."
        ),
    )
    ap.add_argument(
        "--version",
        required=True,
        help="Release version tag (e.g., v2.4.0).",
    )
    ap.add_argument(
        "--dist-root",
        type=pathlib.Path,
        default=DEFAULT_DIST_ROOT,
        help="Root of the dist/ tree to inspect. Default: repo's dist/ directory.",
    )
    ap.add_argument(
        "--output",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT,
        help="Where to write the generated README. Default: dist/README.md.",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated content to stdout instead of writing to --output.",
    )
    return ap


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _make_arg_parser().parse_args(argv)
    rendered = _render(args.version, args.dist_root)

    if args.dry_run:
        sys.stdout.write(rendered)
        return 0

    output_path: pathlib.Path = args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(
        f"Wrote {output_path} ({len(rendered)} bytes, version={args.version}).",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
